"""add assigne email

Revision ID: df08d1fab4e1
Revises: b87bd32f7d04
Create Date: 2026-07-22 11:01:39.346578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df08d1fab4e1'
down_revision: Union[str, None] = 'b87bd32f7d04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('assignee_email', sa.String(length=254), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'assignee_email')
    # ### end Alembic commands ###
